# Generated by Django 3.2 on 2023-11-21 18:21

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20231121_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.validators.validate_date, reviews.validators.validate_score], verbose_name='Год выпуска'),
        ),
    ]
